// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Compiles a Typst template and returns the PDF bytes.
///
/// - `template`   : main .typ file content (UTF-8)
/// - `inputs`     : data injected as sys.inputs (HashMap -> Dict)
/// - `fonts`      : additional font bytes (.ttf/.otf)
/// - `extra_files`: extra files (images, sub-templates)
Future<CompileResult> compile({
  required String template,
  Map<String, String>? inputs,
  required List<Uint8List> fonts,
  required List<TypstFileInput> extraFiles,
}) => RustLib.instance.api.crateApiTypstCompilerCompile(
  template: template,
  inputs: inputs,
  fonts: fonts,
  extraFiles: extraFiles,
);

/// Simplified version — no extra fonts or files.
/// Uses system fonts (typst-kit-fonts feature).
Future<CompileResult> compileSimple({
  required String template,
  Map<String, String>? inputs,
}) => RustLib.instance.api.crateApiTypstCompilerCompileSimple(
  template: template,
  inputs: inputs,
);

/// Returns the version of this plugin's own crate (set in Cargo.toml).
/// Fix 4: typst_as_lib::TYPST_VERSION does not exist —
/// use env! to get our own crate version at compile time instead.
Future<String> typstVersion() =>
    RustLib.instance.api.crateApiTypstCompilerTypstVersion();

/// Result of a successful compilation.
class CompileResult {
  /// Generated PDF bytes — ready to save or display.
  final Uint8List pdfBytes;

  /// Non-fatal warnings emitted by the Typst compiler.
  final List<String> warnings;

  const CompileResult({required this.pdfBytes, required this.warnings});

  @override
  int get hashCode => pdfBytes.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompileResult &&
          runtimeType == other.runtimeType &&
          pdfBytes == other.pdfBytes &&
          warnings == other.warnings;
}

/// Extra file (image, .typ include) for the compiler.
/// `path` is the virtual path used in the template (e.g. "logo.png")
class TypstFileInput {
  final String path;
  final Uint8List data;

  const TypstFileInput({required this.path, required this.data});

  @override
  int get hashCode => path.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstFileInput &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          data == other.data;
}
